# Generated by Django 5.2.4 on 2026-01-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodOrdering', '0002_optiongroup_alter_orderitem_unique_together_option_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=140, unique=True),
        ),
    ]
