# Generated by Django 5.2.4 on 2026-01-20 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodOrdering', '0005_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablereservation',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='tablereservation',
            name='phone',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='tablereservation',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='new', max_length=20),
        ),
    ]
